package com.kiki.video.api.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    USER_NOT_FOUND,
    VIDEO_NOT_FOUND,
    VIDEO_FILE_REQUIRED,
    UNSUPPORTED_VIDEO_TYPE,
    VIDEO_FILE_TOO_LARGE,
    VIDEO_STORAGE_ERROR,
    INVALID_VIDEO_TITLE,
    INVALID_RANGE,
    INTERNAL_ERROR
}
